# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FifaWorldCup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FifaWorldCup
pod 'Alamofire'

end

target 'FifaWorldCup WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FifaWorldCup WatchKit App
pod 'Alamofire'

end

target 'FifaWorldCup WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FifaWorldCup WatchKit Extension
pod 'Alamofire'

end
